# FIT5196 Task 4 in Assessment 2
#### Student Name: Boyu Zhang
#### Student ID: 28491300

Date: XX/XX/XXXX

Version: 1.0

Environment: Python 3.6 and Jupyter notebook

Libraries used: please include the main libraries you used in your assignment here, e.g.,:
* pandas (for dataframe, included in Anaconda Python ) 
* re (for regular expression, included in Anaconda Python 3.6) 
* numpy (for numpy array, included in Anaconda Python 3.6) 
* sklearn (for machine learning algorithm, obtained with `conda install scikit-learn`)

## 1.  Import libraries

In [1]:
# Code to import libraries as you need in this assessment, e.g.,
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import LocalOutlierFactor
%pylab inline

Populating the interactive namespace from numpy and matplotlib

## 2. Load data and exploration

In [2]:
df4 = pd.read_csv('./Input/dataset4_with_outliers.csv')

In [3]:
df4.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long
0,5437400630,20141016T000000,625000.0,4,2.25,1920,8259,2.0,0,0,4,8,1920,0,1979,0,98027,47.5616,-122.088
1,3999300290,20141016T000000,850000.0,3,3.50,2620,11148,2.0,0,4,4,9,2060,560,1977,0,98008,47.5845,-122.115
2,2525059134,20141016T000000,500000.0,2,1.50,1760,12000,1.0,0,0,4,7,1760,0,1964,0,98052,47.6288,-122.109
3,1862400285,20141016T000000,375000.0,3,1.00,1200,5404,1.0,0,0,3,6,1200,0,1937,0,98117,47.6969,-122.368
4,7199320190,20141016T000000,618000.0,4,2.25,2470,7350,1.0,0,0,3,7,1600,870,1978,0,98052,47.6936,-122.128

In [4]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9996 entries, 0 to 9995
Data columns (total 19 columns):
id               9996 non-null int64
date             9996 non-null object
price            9996 non-null float64
bedrooms         9996 non-null int64
bathrooms        9996 non-null float64
sqft_living      9996 non-null int64
sqft_lot         9996 non-null int64
floors           9996 non-null float64
waterfront       9996 non-null int64
view             9996 non-null int64
condition        9996 non-null int64
grade            9996 non-null int64
sqft_above       9996 non-null int64
sqft_basement    9996 non-null int64
yr_built         9996 non-null int64
yr_renovated     9996 non-null int64
zipcode          9996 non-null int64
lat              9996 non-null float64
long             9996 non-null float64
dtypes: float64(5), int64(13), object(1)
memory usage: 1.4+ MB

## 2. Naive feature selection

- We propose to use cluster model to detect the outliers
- We represent each record as a point in high-dimension space
- Thus, we need to elinamet some features that will certainly cause errors.

### Reasoning
- `id` is just a unique identification for each record, should not be used to 
- `date` is categorical data thus cannot be represented in coordinate, need to be dropped
- `zipcode`,`lat` and `long` are all geological-location-related infos, even these values distinguish from others cannot be regarded as an evidence of being outliers at all, we don't pick them for analysis\
### Decision
So we use the remaining 14 columns to find the outliers

## 3. Method selection
- We know that quite a few of the features are correlated but we don't know the exact correlation
- With boxplot we can only determine the outliers based on statics of this single feature, however feautures are correlated so this is not acceptable
### Desion
We choose a cluster model which is suitable for moderately large dataset, which is the `Local Outlier Factor`

### LOF explained

In [5]:
X = df4.drop(columns=['id','date','zipcode','lat','long'])

- Here we need to determine the optimal **K** for the KNN queries, so that the model can perform the best
- Sicnce the LOF model doesn't support Cross-validation for it has no score suitable method, we just use the convention that `k = sqrt(n)`

In [6]:
 k = sqrt(df4.shape[0])

In [7]:
lof =  LocalOutlierFactor(int(k))

In [8]:
df4['is_outlier'] = lof.fit_predict(X)

In [9]:
df4[df4.is_outlier == -1]

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,is_outlier
7,5561000430,20141016T000000,470000.0,3,2.25,1830,39165,1.0,0,0,5,8,1830,0,1963,0,98027,47.4612,-121.992,-1
10,1924079090,20141016T000000,530000.0,3,2.75,2440,45738,2.0,0,0,3,8,1840,600,1987,0,98027,47.5453,-121.957,-1
32,7004200060,20141017T000000,309600.0,4,1.75,1275,20000,1.0,0,0,4,6,1275,0,1991,0,98070,47.3796,-122.490,-1
67,4046600220,20141017T000000,418000.0,3,1.75,1500,19113,1.0,0,0,3,7,1500,0,1984,0,98014,47.6976,-121.916,-1
73,3541700170,20141017T000000,324450.0,3,2.00,1420,16000,1.0,0,0,3,7,1420,0,1966,0,98166,47.4780,-122.358,-1
81,3521069150,20141017T000000,431000.0,3,2.50,2440,71002,1.0,0,0,4,9,2440,0,1996,0,98022,47.2689,-122.010,-1
82,1561600056,20141017T000000,1735000.0,4,3.50,4010,9654,2.0,0,0,3,10,4010,0,2007,0,98004,47.5891,-122.200,-1
86,1221039066,20141017T000000,310000.0,4,2.50,3140,22100,1.0,0,0,4,8,1820,1320,1960,0,98023,47.3190,-122.362,-1
88,722079015,20141017T000000,610000.0,3,2.50,2080,167270,1.0,0,0,3,7,2080,0,2000,0,98038,47.4032,-121.963,-1
94,821079102,20141017T000000,780000.0,4,3.50,3720,213073,1.0,0,2,3,10,3720,0,2007,0,98010,47.3216,-121.940,-1
105,5561400610,20141019T000000,542500.0,5,3.50,2730,42500,1.0,0,0,3,8,1530,1200,1989,0,98027,47.4587,-121.996,-1
111,1723099031,20141020T000000,724950.0,4,3.50,3010,174240,2.0,0,0,3,9,3010,0,2004,0,98045,47.4775,-121.691,-1
116,687600110,20141020T000000,778000.0,3,2.25,2260,33080,1.0,0,0,5,9,1690,570,1974,0,98005,47.6386,-122.183,-1
120,2624079022,20141020T000000,530000.0,3,2.25,1880,100623,1.5,0,0,3,8,1880,0,1987,2007,98024,47.5342,-121.883,-1
126,1841500050,20141020T000000,334950.0,4,1.75,1700,40973,1.0,0,0,3,8,1700,0,1961,0,98031,47.3439,-122.198,-1
140,4053200566,20141020T000000,425000.0,4,2.25,3680,26266,2.0,0,0,4,9,3680,0,1981,0,98042,47.3219,-122.085,-1
144,1330910370,20141020T000000,897500.0,4,3.00,4370,217882,2.0,0,0,3,10,4370,0,1984,0,98053,47.6573,-122.034,-1
148,3345100184,20141020T000000,443950.0,3,1.75,2000,36000,1.0,0,0,3,6,2000,0,1946,1995,98056,47.5217,-122.182,-1
150,3321079060,20141020T000000,378000.0,3,1.75,2610,117176,1.0,0,0,3,7,1390,1220,1981,0,98022,47.2585,-121.925,-1
152,2600100180,20141020T000000,555000.0,4,2.75,2600,19275,1.0,0,0,3,8,1620,980,1978,0,98006,47.5523,-122.162,-1
155,3421069020,20141020T000000,314000.0,3,1.75,1350,217852,1.0,0,0,3,8,1100,250,1953,0,98022,47.2628,-122.030,-1
157,5476800201,20141020T000000,295000.0,3,2.00,1830,17321,1.0,0,0,4,7,1100,730,1948,0,98178,47.5072,-122.272,-1
158,1320069249,20141020T000000,192500.0,1,1.00,470,63737,1.0,0,2,5,5,470,0,1924,0,98022,47.2163,-121.984,-1
160,3342103281,20141020T000000,500000.0,4,1.00,1160,20100,1.0,0,0,4,6,820,340,1913,0,98056,47.5175,-122.201,-1
162,5103300020,20141020T000000,765000.0,4,2.50,4040,25752,2.0,0,0,3,10,4040,0,2000,0,98038,47.4579,-122.068,-1
172,3023049143,20141020T000000,640000.0,4,2.50,3420,21344,2.0,0,0,3,9,3420,0,2002,0,98166,47.4500,-122.334,-1
183,3620069036,20141021T000000,265000.0,3,1.75,1820,32666,1.0,0,0,4,7,1820,0,1966,0,98022,47.1803,-121.974,-1
196,3352402250,20141021T000000,119900.0,2,1.00,700,3180,1.0,0,0,3,6,480,220,1951,0,98178,47.4976,-122.262,-1
210,2426059071,20141021T000000,675000.0,3,2.50,2320,98445,1.0,0,0,4,8,1380,940,1978,0,98072,47.7323,-122.116,-1
216,1545807810,20141021T000000,118000.0,1,1.00,670,7957,1.0,0,0,4,6,670,0,1978,0,98038,47.3594,-122.056,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9732,626059220,20150506T000000,532500.0,4,2.00,2220,23750,1.0,0,0,3,7,2220,0,1963,0,98011,47.7759,-122.214,-1
9742,1523069022,20150506T000000,300000.0,3,1.50,1630,82764,1.0,0,0,4,6,1630,0,1948,0,98027,47.4743,-122.026,-1
9746,825079024,20150506T000000,785000.0,3,2.75,2990,207781,2.0,0,0,3,9,2990,0,2000,0,98014,47.6620,-121.944,-1
9749,1623089165,20150506T000000,920000.0,4,3.75,4030,503989,2.0,0,0,3,10,4030,0,2008,0,98045,47.4807,-121.795,-1
9773,3585300415,20150507T000000,620000.0,3,1.75,1680,28046,1.0,0,3,3,8,1180,500,1948,0,98177,47.7648,-122.370,-1
9778,625069064,20150507T000000,625000.0,3,2.25,2570,47480,1.0,0,0,3,9,2570,0,1979,0,98053,47.6854,-122.079,-1
9783,1774220070,20150507T000000,550000.0,4,2.25,2590,36256,2.0,0,0,3,8,2590,0,1978,0,98077,47.7690,-122.094,-1
9796,620069061,20150507T000000,450000.0,3,2.50,2880,426452,2.0,0,3,3,7,2880,0,1979,0,98092,47.2485,-122.101,-1
9818,2320069111,20150507T000000,449999.0,4,1.75,2290,36900,1.5,0,2,5,7,1690,600,1938,0,98022,47.2034,-122.003,-1
9820,1422069070,20150507T000000,472000.0,3,2.50,1860,415126,2.0,0,0,3,7,1860,0,2006,0,98038,47.3974,-122.005,-1
9834,8011100050,20150508T000000,350000.0,2,1.00,1220,28703,1.0,0,0,4,7,1220,0,1953,0,98056,47.4952,-122.172,-1
9836,3325069025,20150508T000000,500000.0,3,1.00,2000,21780,1.0,0,0,3,8,1480,520,1978,0,98074,47.6064,-122.039,-1
9852,1921069101,20150508T000000,399000.0,3,1.75,2170,73616,1.0,0,0,3,7,2170,0,2008,0,98092,47.2881,-122.086,-1
9865,7302000610,20150508T000000,316000.0,4,1.50,2120,46173,2.0,0,0,3,7,2120,0,1974,0,98053,47.6503,-121.968,-1
9867,126039394,20150508T000000,525000.0,4,2.75,2300,26650,1.0,0,0,4,8,2300,0,1950,0,98177,47.7771,-122.362,-1
9871,2424059174,20150508T000000,1999950.0,4,3.25,5640,35006,2.0,0,2,3,11,4900,740,2015,0,98006,47.5491,-122.104,-1
9879,3422059208,20150511T000000,390000.0,3,2.50,1930,64904,1.0,0,0,4,8,1930,0,1988,0,98042,47.3460,-122.157,-1
9892,2421059090,20150511T000000,640000.0,4,2.50,4090,215186,2.0,0,0,4,8,3670,420,1979,0,98092,47.2964,-122.116,-1
9893,1240700006,20150511T000000,870000.0,3,2.00,2320,65340,1.5,0,0,3,9,2320,0,1992,0,98074,47.6106,-122.055,-1
9919,7932000041,20150512T000000,602500.0,2,2.50,3090,47044,1.0,0,0,4,10,2250,840,1979,0,98058,47.4291,-122.177,-1
9921,5153200356,20150512T000000,280000.0,4,1.75,2250,16000,1.0,0,0,3,8,1450,800,1957,0,98023,47.3303,-122.351,-1
9923,522069119,20150512T000000,550000.0,3,2.50,2720,62310,1.0,0,0,3,8,2040,680,1985,0,98038,47.4168,-122.074,-1
9925,9485940290,20150512T000000,464950.0,4,2.25,2350,36116,1.0,0,0,4,9,2350,0,1983,0,98042,47.3533,-122.082,-1
9932,1775700011,20150512T000000,390000.0,3,2.50,1410,26375,1.0,0,0,3,6,1410,0,1992,0,98077,47.7432,-122.076,-1
9943,2722059275,20150512T000000,536000.0,3,2.75,2290,34548,2.0,0,3,4,7,2290,0,1984,0,98042,47.3691,-122.163,-1
9946,3361400980,20150512T000000,135000.0,2,1.00,600,6120,1.0,0,0,3,5,600,0,1943,1989,98168,47.5000,-122.317,-1
9947,2597501190,20150512T000000,270000.0,3,2.25,2080,26574,1.0,0,2,3,7,1380,700,1993,0,98002,47.2846,-122.192,-1
9954,422069067,20150512T000000,276500.0,4,2.25,2380,128937,1.0,0,0,4,7,2380,0,1960,0,98038,47.4253,-122.043,-1
9967,2316400285,20150513T000000,495000.0,4,3.50,2490,18042,2.0,0,0,3,8,2490,0,2003,0,98070,47.4161,-122.441,-1
9989,4166600610,20150514T000000,335000.0,3,2.00,1410,44866,1.0,0,0,4,7,1410,0,1985,0,98023,47.3273,-122.370,-1

In [10]:
df4 = df4[~(df4.is_outlier == -1)]

In [11]:
df4.to_csv('./dataset4_solution.csv',index=False)

## 3. Summary
Give a short summary of your work done above, such as your findings.