In [2]:
import pandas as pd
import numpy as np
%pylab inline

Populating the interactive namespace from numpy and matplotlib

In [4]:
df = pd.read_excel('./basic_indicators.xlsx',skiprows=list(range(5)),names=['x','Country Name']+list(range(22)))

In [5]:
df = df.dropna(axis=1,how='all');df

,Country Name,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,Afghanistan,25,177,70,74,66,120,53,40,34656.032,1142.96,80,63.673,31.7411,NaN,–,NaN
1,Albania,114,40,14,15,12,35,12,6,2926.348,34.75,0,78.345,97.247,NaN,95.5173,NaN
2,Algeria,78,49,25,27,24,41,22,16,40606.052,949.277,24,76.078,75.136,x,97.0622,NaN
3,Andorra,179,9,3,3,3,7,2,1,77.281,–,0,–,100,NaN,–,NaN
4,Angola,17,221,83,88,76,131,55,29,28813.463,1180.97,96,61.547,66.0301,NaN,84.0123,NaN
5,Anguilla,–,–,–,–,–,–,–,–,14.764,–,–,–,–,NaN,–,NaN
6,Antigua and Barbuda,133,26,9,9,8,25,5,4,100.963,1.636,0,76.364,98.95,x,87.0461,NaN
7,Argentina,126,29,11,12,10,26,10,6,43847.430,753.646,8,76.577,98.09,NaN,99.3468,NaN
8,Armenia,118,50,13,15,12,42,12,7,2924.816,40.158,1,74.618,99.7444,NaN,96.0743,NaN
9,Australia,164,9,4,4,3,8,3,2,24125.848,310.703,1,82.896,–,NaN,97.0328,NaN
10,Austria,164,10,4,4,3,8,3,2,8712.137,83.099,0,81.594,–,NaN,–,NaN
11,Azerbaijan,68,95,31,34,28,75,27,18,9725.376,176.026,5,72.026,99.7901,NaN,94.1427,NaN
12,Bahamas,126,24,11,11,10,20,9,6,391.232,5.57,0,75.675,–,NaN,97.5202,x
13,Bahrain,142,23,8,8,7,20,7,3,1425.171,21.489,0,76.9,94.5568,x,96.4285,NaN
14,Bangladesh,62,144,34,37,32,100,28,20,162951.560,3109.72,106,72.489,72.7587,NaN,90.5086,x
15,Barbados,123,18,12,13,11,16,11,8,284.996,3.408,0,75.906,–,NaN,91.0225,NaN
16,Belarus,164,15,4,4,3,12,3,2,9480.042,114.344,0,72.926,99.6171,x,95.3602,NaN
17,Belgium,164,10,4,4,4,8,3,2,11358.379,128.957,1,81.134,–,NaN,98.9478,NaN
18,Belize,106,39,15,16,13,32,13,10,366.954,8.181,0,70.384,–,NaN,96.1412,NaN
19,Benin,7,178,98,102,93,107,63,31,10872.298,396.613,38,60.907,32.9488,NaN,95.8666,NaN
20,Bhutan,66,128,32,36,29,90,27,18,797.765,14.528,0,70.197,57.0336,NaN,85.5824,NaN
21,Bolivia (Plurinational State of),58,124,37,40,33,85,30,19,10887.882,252.768,9,69.125,92.4551,NaN,88.4827,NaN
22,Bosnia and Herzegovina,153,18,6,7,5,16,5,5,3516.816,32.523,0,76.911,96.9918,NaN,–,NaN
23,Botswana,56,54,41,44,37,42,33,26,2250.260,53.332,2,66.797,81.1887,x,91.0209,NaN
24,Brazil,106,64,15,16,14,53,14,8,207652.865,2965.62,45,75.509,91.7294,NaN,92.6971,NaN
25,British Virgin Islands,–,–,–,–,–,–,–,–,30.661,–,–,–,–,NaN,–,NaN
26,Brunei Darussalam,131,13,10,11,9,10,9,4,423.196,6.73,0,77.203,96.0856,NaN,–,NaN
27,Bulgaria,142,18,8,8,7,15,7,4,7131.494,66.913,1,74.749,98.3525,NaN,93.3048,NaN
28,Burkina Faso,16,199,85,89,80,99,53,26,18646.433,715.598,60,60.361,34.5994,NaN,69.0963,NaN
29,Burundi,23,170,72,77,66,103,48,24,10524.117,437.227,31,57.481,61.5697,NaN,94.1483,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,South Asia,–,129,48,48,48,92,39,28.2,1765989.206,35853.3,1713,68.709,67.6395,NaN,89.8002,NaN
212,Sub-Saharan Africa,–,181,78,84,73,108,53,27.7,1034153.286,37038.5,2860,60.397,65.4588,NaN,80.2069,NaN
213,Eastern and Southern Africa,–,164,61,66,56,101,43,24.5,542206.229,18203,1104,63.3639,75.2131,NaN,81.6126,NaN
214,West and Central Africa,–,199,95,101,89,116,63,30.8,491947.057,18835.5,1756,57.1271,–,NaN,–,NaN
215,Least developed countries,–,176,68,73,63,109,48,26.4,979387.925,31163.1,2101,64.4452,62.9906,NaN,80.6698,NaN
216,World,–,93,41,43,39,65,31,18.6,7427262.841,140462,5642,72.0404,78.4088,NaN,90,**
217,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218,For a complete list of countries and areas in ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
219,It is not advisable to compare data from conse...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
220,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
221,Notes:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
222,– Data not available.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
223,x Data refer to years or periods other than th...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
224,* Data refer to the most recent year available...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
225,** Excludes China.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
226,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
227,Definitions of the indicators:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
228,Under-5 mortality rate – Probability of dying ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
229,Infant mortality rate – Probability of dying b...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
230,Neonatal mortality rate – Probability of dying...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
231,Life expectancy at birth – Number of years new...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
232,Total adult literacy rate – Percentage of popu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
233,Primary school net enrolment ratio – Number of...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
234,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
235,Main data sources:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
236,"Under-5, infant and neonatal mortality rates –...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
237,Total population and births – United Nations P...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
238,Under-five deaths – United Nations Inter-agenc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
239,Life expectancy at birth – United Nations Popu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
240,Total adult literacy rate and primary school e...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df = df.dropna(how='all');df = df[:216];df

,Country Name,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,Afghanistan,25,177,70,74,66,120,53,40,34656.032,1142.96,80,63.673,31.7411,NaN,–,NaN
1,Albania,114,40,14,15,12,35,12,6,2926.348,34.75,0,78.345,97.247,NaN,95.5173,NaN
2,Algeria,78,49,25,27,24,41,22,16,40606.052,949.277,24,76.078,75.136,x,97.0622,NaN
3,Andorra,179,9,3,3,3,7,2,1,77.281,–,0,–,100,NaN,–,NaN
4,Angola,17,221,83,88,76,131,55,29,28813.463,1180.97,96,61.547,66.0301,NaN,84.0123,NaN
5,Anguilla,–,–,–,–,–,–,–,–,14.764,–,–,–,–,NaN,–,NaN
6,Antigua and Barbuda,133,26,9,9,8,25,5,4,100.963,1.636,0,76.364,98.95,x,87.0461,NaN
7,Argentina,126,29,11,12,10,26,10,6,43847.430,753.646,8,76.577,98.09,NaN,99.3468,NaN
8,Armenia,118,50,13,15,12,42,12,7,2924.816,40.158,1,74.618,99.7444,NaN,96.0743,NaN
9,Australia,164,9,4,4,3,8,3,2,24125.848,310.703,1,82.896,–,NaN,97.0328,NaN
10,Austria,164,10,4,4,3,8,3,2,8712.137,83.099,0,81.594,–,NaN,–,NaN
11,Azerbaijan,68,95,31,34,28,75,27,18,9725.376,176.026,5,72.026,99.7901,NaN,94.1427,NaN
12,Bahamas,126,24,11,11,10,20,9,6,391.232,5.57,0,75.675,–,NaN,97.5202,x
13,Bahrain,142,23,8,8,7,20,7,3,1425.171,21.489,0,76.9,94.5568,x,96.4285,NaN
14,Bangladesh,62,144,34,37,32,100,28,20,162951.560,3109.72,106,72.489,72.7587,NaN,90.5086,x
15,Barbados,123,18,12,13,11,16,11,8,284.996,3.408,0,75.906,–,NaN,91.0225,NaN
16,Belarus,164,15,4,4,3,12,3,2,9480.042,114.344,0,72.926,99.6171,x,95.3602,NaN
17,Belgium,164,10,4,4,4,8,3,2,11358.379,128.957,1,81.134,–,NaN,98.9478,NaN
18,Belize,106,39,15,16,13,32,13,10,366.954,8.181,0,70.384,–,NaN,96.1412,NaN
19,Benin,7,178,98,102,93,107,63,31,10872.298,396.613,38,60.907,32.9488,NaN,95.8666,NaN
20,Bhutan,66,128,32,36,29,90,27,18,797.765,14.528,0,70.197,57.0336,NaN,85.5824,NaN
21,Bolivia (Plurinational State of),58,124,37,40,33,85,30,19,10887.882,252.768,9,69.125,92.4551,NaN,88.4827,NaN
22,Bosnia and Herzegovina,153,18,6,7,5,16,5,5,3516.816,32.523,0,76.911,96.9918,NaN,–,NaN
23,Botswana,56,54,41,44,37,42,33,26,2250.260,53.332,2,66.797,81.1887,x,91.0209,NaN
24,Brazil,106,64,15,16,14,53,14,8,207652.865,2965.62,45,75.509,91.7294,NaN,92.6971,NaN
25,British Virgin Islands,–,–,–,–,–,–,–,–,30.661,–,–,–,–,NaN,–,NaN
26,Brunei Darussalam,131,13,10,11,9,10,9,4,423.196,6.73,0,77.203,96.0856,NaN,–,NaN
27,Bulgaria,142,18,8,8,7,15,7,4,7131.494,66.913,1,74.749,98.3525,NaN,93.3048,NaN
28,Burkina Faso,16,199,85,89,80,99,53,26,18646.433,715.598,60,60.361,34.5994,NaN,69.0963,NaN
29,Burundi,23,170,72,77,66,103,48,24,10524.117,437.227,31,57.481,61.5697,NaN,94.1483,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,Turks and Caicos Islands,–,–,–,–,–,–,–,–,34.900,–,–,–,–,NaN,–,NaN
187,Tuvalu,78,57,25,28,23,44,21,17,11.097,–,0,–,–,NaN,84.4011,NaN
188,Uganda,43,175,53,58,48,104,38,21,41487.965,1715.49,90,59.889,70.1982,NaN,93.6503,NaN
189,Ukraine,133,19,9,10,8,17,8,5,44438.625,479.168,4,71.96,99.9744,NaN,96.1755,NaN
190,United Arab Emirates,142,17,8,9,7,14,7,4,9269.612,91.583,1,77.256,90.0339,x,93.375,NaN
191,United Kingdom,164,9,4,5,4,8,4,3,65788.574,805.499,3,81.565,–,NaN,99.8543,NaN
192,United Republic of Tanzania,36,179,57,60,53,108,40,22,55572.201,2086.73,117,65.675,77.8872,NaN,80.0905,NaN
193,United States,151,11,7,7,6,9,6,4,322179.605,4002.52,26,79.392,–,NaN,93.7542,NaN
194,Uruguay,133,23,9,10,8,21,8,5,3444.006,48.546,0,77.493,98.5239,NaN,94.2177,NaN
195,Uzbekistan,80,72,24,27,21,59,21,14,31446.795,663.073,16,71.314,99.9838,NaN,94.6949,NaN
196,Vanuatu,73,36,28,30,25,29,23,12,270.402,6.93,0,72.133,74,x,85.8138,NaN
197,Venezuela (Bolivarian Republic of),100,30,16,18,15,25,14,10,31568.179,602.103,10,74.545,97.1271,NaN,89.8568,NaN
198,Viet Nam,82,51,22,25,18,37,17,12,94569.072,1581.76,34,76.253,93.5204,x,97.9651,NaN
199,Yemen,38,126,55,59,51,88,43,27,27584.213,867.303,48,64.953,–,NaN,84.8373,NaN
200,Zambia,33,182,63,68,58,110,44,23,16591.390,620.261,39,61.874,83.0077,x,87.4041,NaN
201,Zimbabwe,37,75,56,62,51,50,40,23,16150.362,535.37,30,61.163,88.6934,NaN,85.8624,NaN
203,SUMMARY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
204,East Asia and Pacific,–,57,16,18,15,43,14,8.3,2291491.742,31392.7,510,75.3232,–,NaN,93.7572,**
205,Europe and Central Asia,–,31,10,11,9,25,8,5.1,908161.263,11086.6,107,77.35,–,NaN,96.4937,NaN
206,Eastern Europe and Central Asia,–,47,14,16,13,38,13,7.4,416914.481,6138.99,88,72.6579,98.1123,NaN,94.3915,NaN
207,Western Europe,–,11,4,4,4,9,3,2.3,491246.782,4947.65,19,81.3337,–,NaN,98.2646,NaN
208,Latin America and Caribbean,–,55,18,19,16,44,15,9.2,633772.608,10748.9,187,75.5157,93.5486,NaN,93.191,NaN
209,Middle East and North Africa,–,66,24,26,22,50,20,13.6,435225.309,9952.54,237,73.5015,77.7185,NaN,94.0352,NaN
210,North America,–,11,6,7,6,9,6,3.7,358469.427,4389.25,28,79.6939,–,NaN,94.2348,NaN
211,South Asia,–,129,48,48,48,92,39,28.2,1765989.206,35853.3,1713,68.709,67.6395,NaN,89.8002,NaN
212,Sub-Saharan Africa,–,181,78,84,73,108,53,27.7,1034153.286,37038.5,2860,60.397,65.4588,NaN,80.2069,NaN
213,Eastern and Southern Africa,–,164,61,66,56,101,43,24.5,542206.229,18203,1104,63.3639,75.2131,NaN,81.6126,NaN
214,West and Central Africa,–,199,95,101,89,116,63,30.8,491947.057,18835.5,1756,57.1271,–,NaN,–,NaN
215,Least developed countries,–,176,68,73,63,109,48,26.4,979387.925,31163.1,2101,64.4452,62.9906,NaN,80.6698,NaN
216,World,–,93,41,43,39,65,31,18.6,7427262.841,140462,5642,72.0404,78.4088,NaN,90,**

In [9]:
df = df.drop(axis=1,columns=[13,15]);df

,Country Name,0,1,2,3,4,5,6,7,8,9,10,11,12,14
0,Afghanistan,25,177,70,74,66,120,53,40,34656.032,1142.96,80,63.673,31.7411,–
1,Albania,114,40,14,15,12,35,12,6,2926.348,34.75,0,78.345,97.247,95.5173
2,Algeria,78,49,25,27,24,41,22,16,40606.052,949.277,24,76.078,75.136,97.0622
3,Andorra,179,9,3,3,3,7,2,1,77.281,–,0,–,100,–
4,Angola,17,221,83,88,76,131,55,29,28813.463,1180.97,96,61.547,66.0301,84.0123
5,Anguilla,–,–,–,–,–,–,–,–,14.764,–,–,–,–,–
6,Antigua and Barbuda,133,26,9,9,8,25,5,4,100.963,1.636,0,76.364,98.95,87.0461
7,Argentina,126,29,11,12,10,26,10,6,43847.430,753.646,8,76.577,98.09,99.3468
8,Armenia,118,50,13,15,12,42,12,7,2924.816,40.158,1,74.618,99.7444,96.0743
9,Australia,164,9,4,4,3,8,3,2,24125.848,310.703,1,82.896,–,97.0328
10,Austria,164,10,4,4,3,8,3,2,8712.137,83.099,0,81.594,–,–
11,Azerbaijan,68,95,31,34,28,75,27,18,9725.376,176.026,5,72.026,99.7901,94.1427
12,Bahamas,126,24,11,11,10,20,9,6,391.232,5.57,0,75.675,–,97.5202
13,Bahrain,142,23,8,8,7,20,7,3,1425.171,21.489,0,76.9,94.5568,96.4285
14,Bangladesh,62,144,34,37,32,100,28,20,162951.560,3109.72,106,72.489,72.7587,90.5086
15,Barbados,123,18,12,13,11,16,11,8,284.996,3.408,0,75.906,–,91.0225
16,Belarus,164,15,4,4,3,12,3,2,9480.042,114.344,0,72.926,99.6171,95.3602
17,Belgium,164,10,4,4,4,8,3,2,11358.379,128.957,1,81.134,–,98.9478
18,Belize,106,39,15,16,13,32,13,10,366.954,8.181,0,70.384,–,96.1412
19,Benin,7,178,98,102,93,107,63,31,10872.298,396.613,38,60.907,32.9488,95.8666
20,Bhutan,66,128,32,36,29,90,27,18,797.765,14.528,0,70.197,57.0336,85.5824
21,Bolivia (Plurinational State of),58,124,37,40,33,85,30,19,10887.882,252.768,9,69.125,92.4551,88.4827
22,Bosnia and Herzegovina,153,18,6,7,5,16,5,5,3516.816,32.523,0,76.911,96.9918,–
23,Botswana,56,54,41,44,37,42,33,26,2250.260,53.332,2,66.797,81.1887,91.0209
24,Brazil,106,64,15,16,14,53,14,8,207652.865,2965.62,45,75.509,91.7294,92.6971
25,British Virgin Islands,–,–,–,–,–,–,–,–,30.661,–,–,–,–,–
26,Brunei Darussalam,131,13,10,11,9,10,9,4,423.196,6.73,0,77.203,96.0856,–
27,Bulgaria,142,18,8,8,7,15,7,4,7131.494,66.913,1,74.749,98.3525,93.3048
28,Burkina Faso,16,199,85,89,80,99,53,26,18646.433,715.598,60,60.361,34.5994,69.0963
29,Burundi,23,170,72,77,66,103,48,24,10524.117,437.227,31,57.481,61.5697,94.1483
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,Turks and Caicos Islands,–,–,–,–,–,–,–,–,34.900,–,–,–,–,–
187,Tuvalu,78,57,25,28,23,44,21,17,11.097,–,0,–,–,84.4011
188,Uganda,43,175,53,58,48,104,38,21,41487.965,1715.49,90,59.889,70.1982,93.6503
189,Ukraine,133,19,9,10,8,17,8,5,44438.625,479.168,4,71.96,99.9744,96.1755
190,United Arab Emirates,142,17,8,9,7,14,7,4,9269.612,91.583,1,77.256,90.0339,93.375
191,United Kingdom,164,9,4,5,4,8,4,3,65788.574,805.499,3,81.565,–,99.8543
192,United Republic of Tanzania,36,179,57,60,53,108,40,22,55572.201,2086.73,117,65.675,77.8872,80.0905
193,United States,151,11,7,7,6,9,6,4,322179.605,4002.52,26,79.392,–,93.7542
194,Uruguay,133,23,9,10,8,21,8,5,3444.006,48.546,0,77.493,98.5239,94.2177
195,Uzbekistan,80,72,24,27,21,59,21,14,31446.795,663.073,16,71.314,99.9838,94.6949
196,Vanuatu,73,36,28,30,25,29,23,12,270.402,6.93,0,72.133,74,85.8138
197,Venezuela (Bolivarian Republic of),100,30,16,18,15,25,14,10,31568.179,602.103,10,74.545,97.1271,89.8568
198,Viet Nam,82,51,22,25,18,37,17,12,94569.072,1581.76,34,76.253,93.5204,97.9651
199,Yemen,38,126,55,59,51,88,43,27,27584.213,867.303,48,64.953,–,84.8373
200,Zambia,33,182,63,68,58,110,44,23,16591.390,620.261,39,61.874,83.0077,87.4041
201,Zimbabwe,37,75,56,62,51,50,40,23,16150.362,535.37,30,61.163,88.6934,85.8624
203,SUMMARY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
204,East Asia and Pacific,–,57,16,18,15,43,14,8.3,2291491.742,31392.7,510,75.3232,–,93.7572
205,Europe and Central Asia,–,31,10,11,9,25,8,5.1,908161.263,11086.6,107,77.35,–,96.4937
206,Eastern Europe and Central Asia,–,47,14,16,13,38,13,7.4,416914.481,6138.99,88,72.6579,98.1123,94.3915
207,Western Europe,–,11,4,4,4,9,3,2.3,491246.782,4947.65,19,81.3337,–,98.2646
208,Latin America and Caribbean,–,55,18,19,16,44,15,9.2,633772.608,10748.9,187,75.5157,93.5486,93.191
209,Middle East and North Africa,–,66,24,26,22,50,20,13.6,435225.309,9952.54,237,73.5015,77.7185,94.0352
210,North America,–,11,6,7,6,9,6,3.7,358469.427,4389.25,28,79.6939,–,94.2348
211,South Asia,–,129,48,48,48,92,39,28.2,1765989.206,35853.3,1713,68.709,67.6395,89.8002
212,Sub-Saharan Africa,–,181,78,84,73,108,53,27.7,1034153.286,37038.5,2860,60.397,65.4588,80.2069
213,Eastern and Southern Africa,–,164,61,66,56,101,43,24.5,542206.229,18203,1104,63.3639,75.2131,81.6126
214,West and Central Africa,–,199,95,101,89,116,63,30.8,491947.057,18835.5,1756,57.1271,–,–
215,Least developed countries,–,176,68,73,63,109,48,26.4,979387.925,31163.1,2101,64.4452,62.9906,80.6698
216,World,–,93,41,43,39,65,31,18.6,7427262.841,140462,5642,72.0404,78.4088,90

In [10]:
df = df.drop(labels=203);df

,Country Name,0,1,2,3,4,5,6,7,8,9,10,11,12,14
0,Afghanistan,25,177,70,74,66,120,53,40,34656.032,1142.96,80,63.673,31.7411,–
1,Albania,114,40,14,15,12,35,12,6,2926.348,34.75,0,78.345,97.247,95.5173
2,Algeria,78,49,25,27,24,41,22,16,40606.052,949.277,24,76.078,75.136,97.0622
3,Andorra,179,9,3,3,3,7,2,1,77.281,–,0,–,100,–
4,Angola,17,221,83,88,76,131,55,29,28813.463,1180.97,96,61.547,66.0301,84.0123
5,Anguilla,–,–,–,–,–,–,–,–,14.764,–,–,–,–,–
6,Antigua and Barbuda,133,26,9,9,8,25,5,4,100.963,1.636,0,76.364,98.95,87.0461
7,Argentina,126,29,11,12,10,26,10,6,43847.430,753.646,8,76.577,98.09,99.3468
8,Armenia,118,50,13,15,12,42,12,7,2924.816,40.158,1,74.618,99.7444,96.0743
9,Australia,164,9,4,4,3,8,3,2,24125.848,310.703,1,82.896,–,97.0328
10,Austria,164,10,4,4,3,8,3,2,8712.137,83.099,0,81.594,–,–
11,Azerbaijan,68,95,31,34,28,75,27,18,9725.376,176.026,5,72.026,99.7901,94.1427
12,Bahamas,126,24,11,11,10,20,9,6,391.232,5.57,0,75.675,–,97.5202
13,Bahrain,142,23,8,8,7,20,7,3,1425.171,21.489,0,76.9,94.5568,96.4285
14,Bangladesh,62,144,34,37,32,100,28,20,162951.560,3109.72,106,72.489,72.7587,90.5086
15,Barbados,123,18,12,13,11,16,11,8,284.996,3.408,0,75.906,–,91.0225
16,Belarus,164,15,4,4,3,12,3,2,9480.042,114.344,0,72.926,99.6171,95.3602
17,Belgium,164,10,4,4,4,8,3,2,11358.379,128.957,1,81.134,–,98.9478
18,Belize,106,39,15,16,13,32,13,10,366.954,8.181,0,70.384,–,96.1412
19,Benin,7,178,98,102,93,107,63,31,10872.298,396.613,38,60.907,32.9488,95.8666
20,Bhutan,66,128,32,36,29,90,27,18,797.765,14.528,0,70.197,57.0336,85.5824
21,Bolivia (Plurinational State of),58,124,37,40,33,85,30,19,10887.882,252.768,9,69.125,92.4551,88.4827
22,Bosnia and Herzegovina,153,18,6,7,5,16,5,5,3516.816,32.523,0,76.911,96.9918,–
23,Botswana,56,54,41,44,37,42,33,26,2250.260,53.332,2,66.797,81.1887,91.0209
24,Brazil,106,64,15,16,14,53,14,8,207652.865,2965.62,45,75.509,91.7294,92.6971
25,British Virgin Islands,–,–,–,–,–,–,–,–,30.661,–,–,–,–,–
26,Brunei Darussalam,131,13,10,11,9,10,9,4,423.196,6.73,0,77.203,96.0856,–
27,Bulgaria,142,18,8,8,7,15,7,4,7131.494,66.913,1,74.749,98.3525,93.3048
28,Burkina Faso,16,199,85,89,80,99,53,26,18646.433,715.598,60,60.361,34.5994,69.0963
29,Burundi,23,170,72,77,66,103,48,24,10524.117,437.227,31,57.481,61.5697,94.1483
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185,Turkmenistan,44,86,51,60,42,70,43,22,5662.544,144.35,7,67.835,–,–
186,Turks and Caicos Islands,–,–,–,–,–,–,–,–,34.900,–,–,–,–,–
187,Tuvalu,78,57,25,28,23,44,21,17,11.097,–,0,–,–,84.4011
188,Uganda,43,175,53,58,48,104,38,21,41487.965,1715.49,90,59.889,70.1982,93.6503
189,Ukraine,133,19,9,10,8,17,8,5,44438.625,479.168,4,71.96,99.9744,96.1755
190,United Arab Emirates,142,17,8,9,7,14,7,4,9269.612,91.583,1,77.256,90.0339,93.375
191,United Kingdom,164,9,4,5,4,8,4,3,65788.574,805.499,3,81.565,–,99.8543
192,United Republic of Tanzania,36,179,57,60,53,108,40,22,55572.201,2086.73,117,65.675,77.8872,80.0905
193,United States,151,11,7,7,6,9,6,4,322179.605,4002.52,26,79.392,–,93.7542
194,Uruguay,133,23,9,10,8,21,8,5,3444.006,48.546,0,77.493,98.5239,94.2177
195,Uzbekistan,80,72,24,27,21,59,21,14,31446.795,663.073,16,71.314,99.9838,94.6949
196,Vanuatu,73,36,28,30,25,29,23,12,270.402,6.93,0,72.133,74,85.8138
197,Venezuela (Bolivarian Republic of),100,30,16,18,15,25,14,10,31568.179,602.103,10,74.545,97.1271,89.8568
198,Viet Nam,82,51,22,25,18,37,17,12,94569.072,1581.76,34,76.253,93.5204,97.9651
199,Yemen,38,126,55,59,51,88,43,27,27584.213,867.303,48,64.953,–,84.8373
200,Zambia,33,182,63,68,58,110,44,23,16591.390,620.261,39,61.874,83.0077,87.4041
201,Zimbabwe,37,75,56,62,51,50,40,23,16150.362,535.37,30,61.163,88.6934,85.8624
204,East Asia and Pacific,–,57,16,18,15,43,14,8.3,2291491.742,31392.7,510,75.3232,–,93.7572
205,Europe and Central Asia,–,31,10,11,9,25,8,5.1,908161.263,11086.6,107,77.35,–,96.4937
206,Eastern Europe and Central Asia,–,47,14,16,13,38,13,7.4,416914.481,6138.99,88,72.6579,98.1123,94.3915
207,Western Europe,–,11,4,4,4,9,3,2.3,491246.782,4947.65,19,81.3337,–,98.2646
208,Latin America and Caribbean,–,55,18,19,16,44,15,9.2,633772.608,10748.9,187,75.5157,93.5486,93.191
209,Middle East and North Africa,–,66,24,26,22,50,20,13.6,435225.309,9952.54,237,73.5015,77.7185,94.0352
210,North America,–,11,6,7,6,9,6,3.7,358469.427,4389.25,28,79.6939,–,94.2348
211,South Asia,–,129,48,48,48,92,39,28.2,1765989.206,35853.3,1713,68.709,67.6395,89.8002
212,Sub-Saharan Africa,–,181,78,84,73,108,53,27.7,1034153.286,37038.5,2860,60.397,65.4588,80.2069
213,Eastern and Southern Africa,–,164,61,66,56,101,43,24.5,542206.229,18203,1104,63.3639,75.2131,81.6126
214,West and Central Africa,–,199,95,101,89,116,63,30.8,491947.057,18835.5,1756,57.1271,–,–
215,Least developed countries,–,176,68,73,63,109,48,26.4,979387.925,31163.1,2101,64.4452,62.9906,80.6698
216,World,–,93,41,43,39,65,31,18.6,7427262.841,140462,5642,72.0404,78.4088,90

In [11]:
df = df.rename(columns={14:13})

0               34656.032
1                2926.348
2               40606.052
3                  77.281
4               28813.463
5                  14.764
6                 100.963
7                43847.43
8                2924.816
9               24125.848
10               8712.137
11               9725.376
12                391.232
13               1425.171
14              162951.56
15                284.996
16               9480.042
17              11358.379
18                366.954
19              10872.298
20                797.765
21              10887.882
22               3516.816
23                2250.26
24             207652.865
25                 30.661
26                423.196
27               7131.494
28              18646.433
29              10524.117
              ...
185              5662.544
186                  34.9
187                11.097
188             41487.965
189             44438.625
190              9269.612
191             65788.574
192             55572.201
193            322179.605
194              3444.006
195             31446.795
196               270.402
197             31568.179
198             94569.072
199             27584.213
200              16591.39
201             16150.362
204     2291491.742000001
205            908161.263
206            416914.481
207            491246.782
208     633772.6080000001
209            435225.309
210    358469.42699999997
211    1765989.2060000002
212    1034153.2859999997
213     542206.2289999999
214    491947.05700000003
215     979387.9249999996
216     7427262.841000001
Name: 8, Length: 215, dtype: object

In [15]:
df.dtypes

Country Name     object
0                object
1                object
2                object
3                object
4                object
5                object
6                object
7                object
8               float64
9                object
10               object
11               object
12               object
13               object
dtype: object

In [ ]:
df = df.apply(lambda x : x.apply(lambda elt: str(int(elt)) if isinstance(elt, float) else str(elt)));df

In [ ]:
df = df.apply(lambda x: x.str.replace('–',''),axis=1);df

In [ ]:
df.to_csv('./test_out.csv',index=False)